// Replace with your request types
export const REGISTER_USER_DETAILS = "REGISTER_USER_DETAILS";
export const REGISTERATION_SUCCESS = "REGISTRATION_SUCCESS";
export const SUBMIT_USER_DETAILS = "SUBMIT_USER_DETAILS";
export const CLEAR_REGISTRATION_DATA = "CLEAR_REGISTRATION_DATA";
